### ISSUE TITLE
Some text is not visible in Minwaita-Dark

### ISSUE THREAD

**Issue by Ledarium** [godlyranchdressing/Minwaita#1]
I am using gtk3 version 3.22.10 and minwaita 1.3.1. Inactive element font have the same color as background, I suppose. Problem exists in a number of applications (besides chromium). You can see comparsion of dark and light themes below.

![2017-04-30-150800_1366x768_scrot](https://cloud.githubusercontent.com/assets/10389237/25564215/f1b816b8-2db6-11e7-9112-e0a3368645a5.png)
![2017-04-30-150617_1366x768_scrot](https://cloud.githubusercontent.com/assets/10389237/25564216/f1bb248e-2db6-11e7-87d5-154bb65eb901.png)

**Comment by godlyranchdressing** [comment]
What are the other apps? I'm suspecting it's a GTK2 issue.

**Comment by Ledarium** [comment]
I had found similar issue with PCManFM (but the text here is visible)
Also checkboxes are missing, so I'm agree about GTK2.
![2017-04-30-201142_427x344_escrotum](https://cloud.githubusercontent.com/assets/10389237/25566457/9f2da482-2de1-11e7-8e7c-7a358c3b7961.png)
![2017-04-30-201106_427x344_escrotum](https://cloud.githubusercontent.com/assets/10389237/25566458/9f34a494-2de1-11e7-90e6-465713d38ab5.png)

**Comment by godlyranchdressing** [comment]
Fixed. Insensitive text was indeed using the same color as the background. Checkbox issue was due to the checkbox pointing to the wrongly named asset.
