### ISSUE TITLE
Create a variant that preserves original Adwaita colors 

### ISSUE THREAD

**Issue by ranrin** [godlyranchdressing/Minwaita#10]
[example](https://i.imgur.com/E215Y9t.jpg)

**Comment by godlyranchdressing** [comment]
I plan to. I wanted to take ownership of the old adwaita-compact repo and just push it there. Make that _Adwaita-Compact and nothing else_ but I haven't gotten a response from abihf. I might end up just making a new repo.

**Comment by godlyranchdressing** [comment]
Closed with [Adwaita-Slim](https://github.com/godlyranchdressing/Adwaita-Slim).
