### ISSUE TITLE
Checkboxes are invisible in paprefs program

### ISSUE THREAD

**Issue by Poyeyo** [godlyranchdressing/Minwaita#12]
Install paprefs (Pulse Audio Preferences).

Run.

The checkboxes are invisible and can't be used.

**Comment by godlyranchdressing** [comment]
Seems to be working fine for me. What version are you using? You could try one of the archives in the repo itself, they're based on the last push I made so maybe the problem was solved some time ago. 

I just did a little cleanup for the GTK2 theme as well.

**Comment by Poyeyo** [comment]
I removed my downloaded version, installed the PPA version, and the issue is fixed.
