### ISSUE TITLE
Darker areas in MATE desktop & synaptic.

### ISSUE THREAD

**Issue by ghost** [godlyranchdressing/Minwaita#14]
The theme behaves strange on MATE (GTK3) and other commonly used apps in Debian such as synaptic package manager.

![pantallazo-2017-07-18 18-39-57](https://user-images.githubusercontent.com/24773698/28344395-96761a14-6be8-11e7-97dc-e5ce9b07598c.png)
![pantallazo-2017-07-18 18-42-04](https://user-images.githubusercontent.com/24773698/28344423-d29295ea-6be8-11e7-86cf-357f1be18092.png)

**Comment by godlyranchdressing** [comment]
I'll look into it. I really need to get around to testing for other DEs.

**Comment by ghost** [comment]
Fixed in the latest commit :D thanks a bunch.
