### ISSUE TITLE
Excessively large icons in some applications

### ISSUE THREAD

**Issue by ifoolb** [godlyranchdressing/Minwaita#16]
including epiphany, the screenshot app itself.
![screenshot from 2017-08-11 10-45-11](https://user-images.githubusercontent.com/22384393/29199781-4ab552dc-7e82-11e7-9ab4-f236668b1978.png)

**Comment by ifoolb** [comment]
sorry, icon theme issue, not related to Minwaita.

**Comment by godlyranchdressing** [comment]
It's alright. I'm curious though, what icon pack was it?

**Comment by ifoolb** [comment]
Faenza originally, but I happened to install minwaita right after replacing the folder icons with the blue version on gnome look, and thus the impression that minwaita went wrong.
