### ISSUE TITLE
Darker varient not included

### ISSUE THREAD

**Issue by AaronBPaden** [godlyranchdressing/Minwaita#17]
The darker variants aren't actually included in the release tarball. It looks like the directory tree isn't created by compile.sh, so it was probably just overlooked.

compile.sh should probably be creating these automatically. I'm not positive this is 100% correct, but this seems to work:
`mkdir -p "$COMPILED_FOLDER"/Minwaita${variant}/Minwaita${variant}{-Dark,-Darker,}/{gnome-shell,gtk-2.0,gtk-3.0}/assets`

**Comment by godlyranchdressing** [comment]
Oh wow. That's embarrassing. I updated the very messy script and the darker variant is included now. 

The script doesn't create any directories ~and I honestly never thought of just creating the directories through the script~. I extract the Compiled archive which has the directory structure for everything to get copied over/compiled and work from that. I'll update it again sometime when I think of a neat way to do it.
