### ISSUE TITLE
Darker theme improvement: Save window

### ISSUE THREAD

**Issue by jeremy447** [godlyranchdressing/Minwaita#19]
Hello,
I really like the darker theme you made and I want to thank you for this ! I found some issue that I will report. Here is the first one :

The "Save" window can be improved for the Darker theme

![screenshot from 2017-08-17 19-40-27](https://user-images.githubusercontent.com/17159065/29458881-852eefaa-8421-11e7-957d-68982eb1c53b.png)

**Comment by godlyranchdressing** [comment]
Thank you.

I've fixed it, the pathbar will use the regular (light) buttons from now on. Will push the changes in a bit.
