### ISSUE TITLE
White line on top panel in Minwaita light theme (Ubuntu 17.10)

### ISSUE THREAD

**Issue by shantanu-csedu** [godlyranchdressing/Minwaita#31]
There is white line in top of top panel in ubuntu 17.10. System is fresh installed. Dark and Darker themes does't have this issue.

I have attached a screenshot. Line is 1 or 2 px thick 
![screenshot from 2017-10-27 03-11-21](https://user-images.githubusercontent.com/5156116/32077369-fd9304fc-bac4-11e7-8ef5-32abdfa3efff.png)

**Comment by corebots** [comment]
I'm seeing this white line too in the top panel when minwaita theme is active and desktop icons are switched on. In Fedora 27 with GNOME 3.26. 

Please is there an easy fix?
