### ISSUE TITLE
Gtk2 theme looks odd

### ISSUE THREAD

**Issue by shantanu-csedu** [godlyranchdressing/Minwaita#32]
Gtk3 theme is awesome but gtk2 looks old and inconsistent. I have attach a screenshot.
![screenshot from 2017-11-02 02-27-56](https://user-images.githubusercontent.com/5156116/32296150-9fbdc33e-bf75-11e7-988e-bce6d7bf6da5.png)

**Comment by godlyranchdressing** [comment]
What distro are you running? Ubuntu 17.10?

**Comment by shantanu-csedu** [comment]
Yes. Fresh installed.

**Comment by godlyranchdressing** [comment]
I installed 17.10 today and was having the same issue with other themes. It only went away after installing the default session (sudo apt install gnome-session). Maybe that might help you too?

**Comment by shantanu-csedu** [comment]
System upgrade fix the issue. I didn't have to install gnome-session.
