### ISSUE TITLE
Chrome maximized - maximized button issue

### ISSUE THREAD

**Issue by corebots** [godlyranchdressing/Minwaita#33]
![screenshot from 2017-11-25 14-27-22](https://user-images.githubusercontent.com/12252430/33230948-fe549d8a-d1ec-11e7-978e-27a4b2cff2c3.png)
the green maximize button disappears when you maximize chrome and is replaced by a generic icon. looks quite odd, please could you have a look?

**Comment by corebots** [comment]
BTW please is this theme still being maintained? thanks

**Comment by godlyranchdressing** [comment]
@corebots yes it is. Sorry about that. I forgot to push the updates. It's on the repo or over at [gnome-look](https://www.gnome-look.org/p/1174686/).

It is still being maintained. I'm just starting over the theme from scratch since things are currently a little messy so I'm a little slow on fixes.

**Comment by corebots** [comment]
wow! thank you so much for the fixes :)
