### ISSUE TITLE
window controls huge after update to Chrome 65

### ISSUE THREAD

**Issue by corebots** [godlyranchdressing/Minwaita#38]
Oops. I've just installed the latest updates to my Fedora 27 which included the new Chrome 65. After reboot Chrome looks like this :D
![screenshot from 2018-03-08 10-15-49](https://user-images.githubusercontent.com/12252430/37143002-107d4f2a-22ba-11e8-9127-ea6449df5fb3.png)

Please could you have a look and fix? Thank you

**Comment by corebots** [comment]
issue seems to be the same with other variants of Minwaita and the new Chrome 65. Is nobody else seeing this?

**Comment by Kuba77cz** [comment]
I have same issue with Manjaro GNOME and Chromium 65.

**Comment by yud1z** [comment]
yes, me too
![image](https://user-images.githubusercontent.com/1138078/39744651-35e41d94-52cf-11e8-9c58-ee3728792625.png)

**Comment by corebots** [comment]
I suddently don't see this anymore; looks like the fault was on Chrome's side?
