### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by asokero** [godlyranchdressing/Minwaita#6]
Hey,

Thanks for this nice looking theme! It would be great to have a license file in this repository as currently it seems to be open source but not free for use, copy or modify. It seems that Arch linux has a package for minwaita and it claims that the theme is GPL, is this true? 
https://aur.archlinux.org/packages/gtk-theme-minwaita/

Maybe you could add this info also to a LICENSE file or similar to make it more clear. This would make it easier to package it to different distributions and such.

**Comment by godlyranchdressing** [comment]
Yes it is. The license file has been uploaded.
