### ISSUE TITLE
Minwaita-Darker?

### ISSUE THREAD

**Issue by schtufbox** [godlyranchdressing/Minwaita#7]
Any chance of a 'darker' variant?
Like the title bar/menus/toolbars and nautilus sidepanel being like the dark, but the rest like the light?

Sort of like the Arc-Darker varient of Arc theme, only with the black colouring of the Minwaita theme on the dark parts? 
Attached a mock-up image.

![minwaita-darker-mockup](https://cloud.githubusercontent.com/assets/27377883/25745929/09271a5c-3199-11e7-8632-60b35ace6d7b.png)

I'd do it myself, but urmm, things have changed since I last did any theming (GTK+ lol) and I have no clue :P

**Comment by godlyranchdressing** [comment]
Yep, I'm working on it. It'll take a while though, I keep scrapping it because I don't like the way I'm going about it. It's a bit frustrating because of the way Adwaita draws its boxes with its fancy gradients.
