### ISSUE TITLE
Gnome Builder is not properly styled

### ISSUE THREAD

**Issue by JohannesKahl** [godlyranchdressing/Minwaita#8]
Hi, i would like to ask if there is any plan to support gnome-builder. So far it's the only application i've tried that has problems with minwaita (you can see from the screenshot below).

![screenshot-2017-05-11-18 27 59](https://cloud.githubusercontent.com/assets/7595097/25960610/b625a4e8-3677-11e7-89f2-5022737c1d7f.png)

Also, thank you for this themes suite. It was needed.

**Comment by godlyranchdressing** [comment]
I'll get on that. I didn't know it looked messed up like that.

**Comment by godlyranchdressing** [comment]
Fixed. The updated version hasn't been released but you can get it in one of the archives for now.
