### ISSUE TITLE
osX controls variation

### ISSUE THREAD

**Issue by corebots** [godlyranchdressing/Minwaita#9]
hello and first of all thanks for this theme. I've tried the osX variant an would like to suggest to speed up the animation to display the 'x' and other signs inside the controls on hover as i've found myself clicking faster then the signs appear; on macOS it's also quicker, i've made a small screencast: https://www.dropbox.com/s/9zr2pmkworld04n/controls.mov?dl=0

also, i was unable to move the windows control to the left (on Fedora 26) as setting close,maximize,minimize: in dConf resulted in a close:maximize,minimize configuration on the actual windows - is there a trick to make the window controls all align left these days? :) thank you

**Comment by godlyranchdressing** [comment]
Thanks so much for including the screencast. I've literally only used macOS probably twice in my life so I didn't know there was basically no animation. I've removed the transition.

I'm using Fedora 25 so I can't say for sure if anything's change but AFAIK anything to the left of the colon stays on the left as opposed to the right. If "close, maximize, minimize:" doesn't align the controls to the left then I guess something must have changed. Though if something _did_ change it'll be a 3.24 change and I had no problem moving the controls to the left in Ubuntu GNOME 17.04.

**Comment by corebots** [comment]
Thanks for the fix ;)

**Comment by corebots** [comment]
please would you also consider to make the signs inside the buttons display all three at once? same as on macOS, you can also see it in my original video.
